config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  post '/rate' => 'rater#create', :as => 'rate'
  root to: 'home#index'

  devise_for :users

  get 'titles/index'
  get 'reviews/index'
  get 'search' => 'search#index'

  get 'titles/search' => 'titles#search'
  get 'titles/:id/poster' => 'titles#poster'
  get 'poster/:imdbId' => 'poster#show'

  resources :titles do
    resources :reviews
  end

  resources :votes
  resources :users
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :title
  validates :content, presence: true

  def getVoteCount
    Vote.where(review_id: id).count
  end
end

app/models/title.rb
class Title < ActiveRecord::Base
  has_many :reviews
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def getReviews
     Review.find_by(user_id: id)
   end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def _index
  end

  def index
    recent_reviews = Review
      .order(created_at: :desc)
      .take(10)

    title_ids = recent_reviews.map { |r| r.title_id }

    @recently_reviewed = Title.find(title_ids)
    @recent_titles = Title
      .order(created_at: :desc)
      .take(10)
  end
end

app/controllers/poster_controller.rb
require "open-uri"

class PosterController < ApplicationController

  def show
    imdbId = params[:imdbId]
    filename = "public/posters/" + imdbId + ".jpeg"

    if !File.file?(filename)
      download_image(imdbId)
    end

    send_file(
      "public/posters/" + imdbId + ".jpeg",
      type: "image/jpeg",
      x_sendfile: true
    )
  end

  private
    def download_image(imdbId)
      url = "http://img.omdbapi.com/?i=" + imdbId  + "&apikey=" + Rails.application.secrets.omdb_api_key
      localPath = "public/posters/" + imdbId + ".jpeg"

      File.open(localPath, "wb") do |saved_file|
        open(url, "rb") do |read_file|
          saved_file.write(read_file.read)
        end
      end
    end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/titles_controller.rb
require 'rest_client'
require 'json'

class TitlesController < ApplicationController

  def index
    @titles = Title.take(10)
  end

  def show
    @title = Title.find(params[:id])
  end

  def new
    @title = Title.new
  end

  def create
    @title = Title.new(title_params)
    @title.save
    redirect_to 'index'
  end

  def search
    term = params[:term]
    json = SearchHelper.searchByTerm(term)
    @results = json.map { |j|
      find = Title.find_by(imdbId: j["imdbID"])
      if find
        find
      else
        newTitle = TitlesHelper.search_json_to_title(j)
        newTitle.save!
        newTitle
      end
    }
  end

  private
    def title_params
      params.require(:title).permit(:description, :imdbId)
    end
end

app/controllers/users_controller.rb
require 'pbkdf2'

class UsersController < ApplicationController
  before_action :authenticate_user!
  @iterations = 10000

  def index
    user = current_user
    @reviews = user.getReviews
  end

  def new
    @user = User.new
  end

  def create
    hash = PBKDF2.new do |p|
      p.password = params[:password]
      p.salt = "nacl"
      p.iterations = @iterations
    end

    params[:password_hash] = hash.hex_string
    params[:salt] = hash.salt

    @user = User.create(user_params)
    redirect_to ''
  end

  def show
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password_hash, :salt)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @review = Review.find(vote_params[:review_id])
    @title = Title.find(@review.title_id)
    @vote = Vote.new(vote_params)

    if !Vote.find_by user_id: current_user.id, review_id: @review.id
      @vote.save
      redirect_to title_path(@title)
    else
      render plain: "Already voted."
    end
  end

  def new
  end

  private
    def vote_params
      params[:vote][:user_id] = current_user.id
      params.require(:vote).permit(:user_id, :review_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/poster_helper.rb
module PosterHelper
end

app/helpers/posters_helper.rb
module PostersHelper
  def download_poster(imdbId)
    url = "http://img.omdbapi.com/?i=" + imdbId  + "&apikey=" + Rails.application.secrets.omdb_api_key
    localPath = "public/posters/" + imdbId + ".jpeg"

    File.open(localPath, "wb") do |saved_file|
      open(url, "rb") do |read_file|
        saved_file.write(read_file.read)
      end
    end
  end
end

app/helpers/postman_helper.rb
module PostmanHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
require 'rest_client'
require 'json'

module SearchHelper

  def self.searchByTerm(term)
    result = RestClient.get(
      "http://www.omdbapi.com/",
      { params: {
        "s" => term,
        "type" => "movie",
        "page" => "1" }
      }
    )
    json = JSON.parse result.to_str
    json["Search"].select { |j| j["Poster"] != "N/A" }
  end
  
end

app/helpers/titles_helper.rb
require 'rest_client'
require 'json'

module TitlesHelper

  def self.download_description(title)
    resultString = RestClient.get(
      "http://www.omdbapi.com/",
      { :params => {
        "i" => title.imdbId,
        "plot" => "short",
        "r" => "json" }
      }
    )

    result = JSON.parse resultString.to_s

    if result["Response"].to_s == "True"
      title.description = result["Plot"]
      title.save
    else
      result["Error"].to_s
    end
  end

  def self.search_json_to_title(j)
    Title.new(
      :title => j["Title"],
      :imdbId => j["imdbID"],
      :year => j["Year"].to_i,
      :description => nil
    )
  end

  def self.import_title(t)
    Title.find_by(imdbId: t.imdbId) || t.save
  end

  def by_imdbId(imdbId)
    Title.find_by imdbId: imdbId
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/posters/_show.html.erb
<a href="<%= title_path(title) %>">
  <img src='<%= "/poster/" + title.imdbId %>'>
</a>

app/views/titles/_title_list.html.erb
<% if label %>
  <div class="row">
    <div class="col-sm-12">
      <h2><%= label.to_s %></h2>
    </div>
  </div>
<% end %>
<% titles.each_slice(2) do |pair| %>
  <div class="row">
    <% pair.each do |t| %>
      <div class="col-sm-6">
        <%= render "/titles/title_summary", title: t, reviews: t.reviews.take(3) %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/titles/_title_summary.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-6">
        <!-- <img src='<%= "/poster/" + title.imdbId %>'> -->
        <%= render "posters/show", title: title %>
      </div>
      <div class="col-sm-6">
        <%= link_to title.title, title_path(title) %>

        <p><%= title.year %></p>
        <p><%= title.description %></p>

        <% reviews.each do |r| %>
          <p>"<%= r.content %>"</p>
          <p><%= render "reviews/display_stars", num_stars: r.ratings %></p>
        <% end %>

        <% if reviews.count == 0 %>
          <%= link_to 'Write a review', title_path(title) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/titles/index.html.erb
<div class="row">
  <div class="col-sm-1">
    <h4>Titles</h4>
  </div>
</div>

<div>
  <% @titles.each_slice(2) do |pair| %>
    <div class="row">
      <% pair.each do |t| %>
        <div class="col-sm-6">
          <%= render "title_summary", title: t, reviews: t.reviews %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/titles/new.html.erb
<%= form_for :title, url: titles_path do |f| %>

  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@title.errors.count, "error") %> prohibited
        this title from being saved:
      </h2>
      <ul>
        <% @title.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', titles_path %>

app/views/titles/search.html.erb
<div class="row">
  <div class="col-sm-1">
    <h4>Search Results</h4>
  </div>
</div>

<div>
  <% @results.each_slice(2) do |pair| %>
    <div class="row">
      <% pair.each do |t| %>
        <div class="col-sm-6">
          <%= render "title_summary", title: t, reviews: t.reviews %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/titles/show.html.erb
<div>
  <div class="row">
    <div class="col-sm-12">
      <strong>Title:</strong> <%= @title.title %>
    </div>
  </div>

  <img src='<%= "/poster/" + @title.imdbId %>'>

  <p>
    <strong>Text:</strong>
    <%= @title.description %>
  </p>

  <h2>Reviews</h2>
  <% @title.reviews.each do |review| %>
    <%= render "/reviews/review_summary", review: review %>
  <% end %>

  <h2>Add a review</h2>

  <%= render "/reviews/write_review", title: @title %>

  <%= link_to 'Back', titles_path %>

</div>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', titles_path %>