config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  post '/rate' => 'rater#create', :as => 'rate'
  root to: 'home#index'

  devise_for :users

  get 'titles/index'
  get 'reviews/index'
  get 'search' => 'search#index'

  get 'titles/search' => 'titles#search'
  get 'titles/:id/poster' => 'titles#poster'
  get 'poster/:imdbId' => 'poster#show'

  resources :titles do
    resources :reviews
  end

  resources :votes
  resources :users
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :title
  validates :content, presence: true

  def getVoteCount
    Vote.where(review_id: id).count
  end
end

app/models/title.rb
class Title < ActiveRecord::Base
  has_many :reviews
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def getReviews
     Review.find_by(user_id: id)
   end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def _index
  end

  def index
    recent_reviews = Review
      .order(created_at: :desc)
      .take(10)

    title_ids = recent_reviews.map { |r| r.title_id }

    @recently_reviewed = Title.find(title_ids)
    @recent_titles = Title
      .order(created_at: :desc)
      .take(10)
  end
end

app/controllers/poster_controller.rb
require "open-uri"

class PosterController < ApplicationController

  def show
    imdbId = params[:imdbId]
    filename = "public/posters/" + imdbId + ".jpeg"

    if !File.file?(filename)
      download_image(imdbId)
    end

    send_file(
      "public/posters/" + imdbId + ".jpeg",
      type: "image/jpeg",
      x_sendfile: true
    )
  end

  private
    def download_image(imdbId)
      url = "http://img.omdbapi.com/?i=" + imdbId  + "&apikey=" + Rails.application.secrets.omdb_api_key
      localPath = "public/posters/" + imdbId + ".jpeg"

      File.open(localPath, "wb") do |saved_file|
        open(url, "rb") do |read_file|
          saved_file.write(read_file.read)
        end
      end
    end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def create
    @title = Title.find(params[:title_id])
    @review = @title.reviews.create(review_params)

    if user_signed_in?
      @review.user_id = current_user.id
      @review.save
    end

    redirect_to title_path(@title)
  end

  private
    def review_params
      params.require(:review).permit(:content, :user, :ratings)
    end
end

app/controllers/users_controller.rb
require 'pbkdf2'

class UsersController < ApplicationController
  before_action :authenticate_user!
  @iterations = 10000

  def index
    user = current_user
    @reviews = user.getReviews
  end

  def new
    @user = User.new
  end

  def create
    hash = PBKDF2.new do |p|
      p.password = params[:password]
      p.salt = "nacl"
      p.iterations = @iterations
    end

    params[:password_hash] = hash.hex_string
    params[:salt] = hash.salt

    @user = User.create(user_params)
    redirect_to ''
  end

  def show
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password_hash, :salt)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @review = Review.find(vote_params[:review_id])
    @title = Title.find(@review.title_id)
    @vote = Vote.new(vote_params)

    if !Vote.find_by user_id: current_user.id, review_id: @review.id
      @vote.save
      redirect_to title_path(@title)
    else
      render plain: "Already voted."
    end
  end

  def new
  end

  private
    def vote_params
      params[:vote][:user_id] = current_user.id
      params.require(:vote).permit(:user_id, :review_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/poster_helper.rb
module PosterHelper
end

app/helpers/posters_helper.rb
module PostersHelper
  def download_poster(imdbId)
    url = "http://img.omdbapi.com/?i=" + imdbId  + "&apikey=" + Rails.application.secrets.omdb_api_key
    localPath = "public/posters/" + imdbId + ".jpeg"

    File.open(localPath, "wb") do |saved_file|
      open(url, "rb") do |read_file|
        saved_file.write(read_file.read)
      end
    end
  end
end

app/helpers/postman_helper.rb
module PostmanHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
require 'rest_client'
require 'json'

module SearchHelper

  def self.searchByTerm(term)
    result = RestClient.get(
      "http://www.omdbapi.com/",
      { params: {
        "s" => term,
        "type" => "movie",
        "page" => "1" }
      }
    )
    json = JSON.parse result.to_str
    json["Search"].select { |j| j["Poster"] != "N/A" }
  end
  
end

app/helpers/titles_helper.rb
require 'rest_client'
require 'json'

module TitlesHelper

  def self.download_description(title)
    resultString = RestClient.get(
      "http://www.omdbapi.com/",
      { :params => {
        "i" => title.imdbId,
        "plot" => "short",
        "r" => "json" }
      }
    )

    result = JSON.parse resultString.to_s

    if result["Response"].to_s == "True"
      title.description = result["Plot"]
      title.save
    else
      result["Error"].to_s
    end
  end

  def self.search_json_to_title(j)
    Title.new(
      :title => j["Title"],
      :imdbId => j["imdbID"],
      :year => j["Year"].to_i,
      :description => nil
    )
  end

  def self.import_title(t)
    Title.find_by(imdbId: t.imdbId) || t.save
  end

  def by_imdbId(imdbId)
    Title.find_by imdbId: imdbId
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/reviews/_display_stars.html.erb
<div>
  <% for i in (0...num_stars) %>
    <span class="glyphicon glyphicon-star ratings-star" aria-hidden="true"></span>
  <% end %>
  <% for i in (0...(5 - num_stars)) %>
    <span class="glyphicon glyphicon-star-empty ratings-star" aria-hidden="true"></span>
  <% end %>
</div>

app/views/reviews/_review_short_summary.erb
<div>
  <div class="row">
    <div class="col-sm-12">
      <div class="centered">
        <%= review.content %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="centered">
        <%= review.ratings %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_review_summary.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <div class="row">

        <div class="col-sm-8">
          <div class="review-content">
            <p>"<%= review.content %>"</p>
          </div>
        </div>

        <div class="col-sm-2">
          <%= render "reviews/display_stars", num_stars: review.ratings.to_int %>
        </div>

        <div class="col-sm-1">
          <%= review.getVoteCount() %> votes
        </div>

        <div class="col-sm-1">
          <% if user_signed_in? %>
            <%= form_for :vote, url: votes_path do |f| %>
              <%= f.hidden_field :review_id, {:value => review.id} %>
              <%= f.submit "Vote" %>
            <% end %>
          <% end %>
        </div>

    </div>

  </div>
</div>

app/views/reviews/_set_stars.html.erb
<div>
  <% for i in (1..5) %>
    <input name="ratings"
           type="radio"
           class="selectable-star"
           aria-hidden="true"
           value="<%= i %>"/>
   <% end %>
</div>

app/views/reviews/_write_review.html.erb
<%= form_for([@title, @title.reviews.build]) do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %><br>
  </p>
  <p>
    <input name="review[ratings]" type="radio" class="star" value="1"/>
    <input name="review[ratings]" type="radio" class="star" value="2"/>
    <input name="review[ratings]" type="radio" class="star" value="3"/>
    <input name="review[ratings]" type="radio" class="star" value="4"/>
    <input name="review[ratings]" type="radio" class="star" value="5"/>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>