config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  post '/rate' => 'rater#create', :as => 'rate'
  root to: 'home#index'

  devise_for :users

  get 'titles/index'
  get 'reviews/index'
  get 'search' => 'search#index'

  get 'titles/search' => 'titles#search'
  get 'titles/:id/poster' => 'titles#poster'
  get 'poster/:imdbId' => 'poster#show'

  resources :titles do
    resources :reviews
  end

  resources :votes
  resources :users
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :title
  validates :content, presence: true

  def getVoteCount
    Vote.where(review_id: id).count
  end
end

app/models/title.rb
class Title < ActiveRecord::Base
  has_many :reviews
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def getReviews
     Review.find_by(user_id: id)
   end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def _index
  end

  def index
    recent_reviews = Review
      .order(created_at: :desc)
      .take(10)

    title_ids = recent_reviews.map { |r| r.title_id }

    @recently_reviewed = Title.find(title_ids)
    @recent_titles = Title
      .order(created_at: :desc)
      .take(10)
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
require 'pbkdf2'

class UsersController < ApplicationController
  before_action :authenticate_user!
  @iterations = 10000

  def index
    user = current_user
    @reviews = user.getReviews
  end

  def new
    @user = User.new
  end

  def create
    hash = PBKDF2.new do |p|
      p.password = params[:password]
      p.salt = "nacl"
      p.iterations = @iterations
    end

    params[:password_hash] = hash.hex_string
    params[:salt] = hash.salt

    @user = User.create(user_params)
    redirect_to ''
  end

  def show
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password_hash, :salt)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @review = Review.find(vote_params[:review_id])
    @title = Title.find(@review.title_id)
    @vote = Vote.new(vote_params)

    if !Vote.find_by user_id: current_user.id, review_id: @review.id
      @vote.save
      redirect_to title_path(@title)
    else
      render plain: "Already voted."
    end
  end

  def new
  end

  private
    def vote_params
      params[:vote][:user_id] = current_user.id
      params.require(:vote).permit(:user_id, :review_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/poster_helper.rb
module PosterHelper
end

app/helpers/posters_helper.rb
module PostersHelper
  def download_poster(imdbId)
    url = "http://img.omdbapi.com/?i=" + imdbId  + "&apikey=" + Rails.application.secrets.omdb_api_key
    localPath = "public/posters/" + imdbId + ".jpeg"

    File.open(localPath, "wb") do |saved_file|
      open(url, "rb") do |read_file|
        saved_file.write(read_file.read)
      end
    end
  end
end

app/helpers/postman_helper.rb
module PostmanHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
require 'rest_client'
require 'json'

module SearchHelper

  def self.searchByTerm(term)
    result = RestClient.get(
      "http://www.omdbapi.com/",
      { params: {
        "s" => term,
        "type" => "movie",
        "page" => "1" }
      }
    )
    json = JSON.parse result.to_str
    json["Search"].select { |j| j["Poster"] != "N/A" }
  end
  
end

app/helpers/titles_helper.rb
require 'rest_client'
require 'json'

module TitlesHelper

  def self.download_description(title)
    resultString = RestClient.get(
      "http://www.omdbapi.com/",
      { :params => {
        "i" => title.imdbId,
        "plot" => "short",
        "r" => "json" }
      }
    )

    result = JSON.parse resultString.to_s

    if result["Response"].to_s == "True"
      title.description = result["Plot"]
      title.save
    else
      result["Error"].to_s
    end
  end

  def self.search_json_to_title(j)
    Title.new(
      :title => j["Title"],
      :imdbId => j["imdbID"],
      :year => j["Year"].to_i,
      :description => nil
    )
  end

  def self.import_title(t)
    Title.find_by(imdbId: t.imdbId) || t.save
  end

  def by_imdbId(imdbId)
    Title.find_by imdbId: imdbId
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Deec</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Search', search_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Edit account', edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
        <li><%= link_to 'Users', users_path %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OwrRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
  <body>
    <div>
      <div class="container-fluid">
        <%= render "layouts/nav" %>
        <%= yield %>
      </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>